In [55]:
import pandas as pd

In [56]:
df=pd.read_csv('tested.csv')

In [57]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S

In [58]:
df.drop(['PassengerId','Name','Ticket','Cabin'],axis=1,
        inplace=True)

In [59]:
df.head(10)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  34.5      0      0   7.8292        Q
1         1       3  female  47.0      1      0   7.0000        S
2         0       2    male  62.0      0      0   9.6875        Q
3         0       3    male  27.0      0      0   8.6625        S
4         1       3  female  22.0      1      1  12.2875        S
5         0       3    male  14.0      0      0   9.2250        S
6         1       3  female  30.0      0      0   7.6292        Q
7         0       2    male  26.0      1      1  29.0000        S
8         1       3  female  18.0      0      0   7.2292        C
9         0       3    male  21.0      2      0  24.1500        S

In [60]:
df.nunique()

Survived      2
Pclass        3
Sex           2
Age          79
SibSp         7
Parch         8
Fare        169
Embarked      3
dtype: int64

In [61]:
df['Sex']=df['Sex'].map({'male':1,'female':0})

In [62]:
df=pd.get_dummies(df,columns=['Embarked'])

In [63]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,34.5,0,0,7.8292,False,True,False
1,1,3,0,47.0,1,0,7.0000,False,False,True
2,0,2,1,62.0,0,0,9.6875,False,True,False
3,0,3,1,27.0,0,0,8.6625,False,False,True
4,1,3,0,22.0,1,1,12.2875,False,False,True

In [64]:
a=df.isnull().sum()
a

Survived       0
Pclass         0
Sex            0
Age           86
SibSp          0
Parch          0
Fare           1
Embarked_C     0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [65]:
df.describe()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,0.363636,2.265550,0.636364,30.272590,0.447368,0.392344,35.627188
std,0.481622,0.841838,0.481622,14.181209,0.896760,0.981429,55.907576
min,0.000000,1.000000,0.000000,0.170000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,21.000000,0.000000,0.000000,7.895800
50%,0.000000,3.000000,1.000000,27.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,1.000000,39.000000,1.000000,0.000000,31.500000
max,1.000000,3.000000,1.000000,76.000000,8.000000,9.000000,512.329200

In [66]:
df.dropna(inplace=True)

In [67]:
df['age']=df["Age"].astype(int)

In [68]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=5,test_size=0.2)

In [71]:
from sklearn.tree import DecisionTreeClassifier

In [72]:
model=DecisionTreeClassifier()

In [73]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [74]:
y_pred=model.predict(x_test)

In [75]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [76]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[44,  0],
       [ 0, 23]])

In [77]:
accy=accuracy_score(y_test,y_pred)
accy*100

100.0